apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: notes-app
type: Opaque
stringData:
  MONGODB_URI: "mongodb+srv://dev7nsh_db_user:flzaGZrDBdnZHJK4@cluster0.h5v9b9p.mongodb.net/?appName=Cluster0"
  PORT: "8086"
  SECRET: "your_secret_key"
