apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: notes-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: notes-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8086
          env:
            - name: PORT
              value: "8086"
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: MONGODB_URI
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: SECRET
